language: clojure
lein: lein2
jdk:
 - oraclejdk7
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq phantomjs
install:
 - lein2 deps
 - lein2 cljx once
script:
 - lein2 test
 - lein2 cljsbuild test
